### ISSUE TITLE
Can't evaluate with evaluate_deepcoder.py

### ISSUE THREAD

**Issue by yichao-liang** [mtensor/neural_sketch#8]
I pretrained the skech generator and dc synthesizer following the instructions with no problem, but got an error when trying evaluate the full model using `python eval/evaluate_deepcoder.py`.

More specifically I got `EOFError: Ran out of input`, with more details shown below. I'm using conda environment, and 1 strange thing is it says `No module named 'numpy' despite I have numpy installed in my environment.

Could you please let me know how I can make it run? I'm trying to experiment with this as a research project. Any help would be much appreciated! Thanks a lot!

```
$ python eval/evaluate_deepcoder.py
loading model with holes
data file: data/T3_test_data_new.p
/home/yliang/miniconda3/envs/sketch/lib/python3.7/site-packages/torch/nn/functional.py:1374: UserWarning: nn.functiona
l.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
25
[(lambda (lambda (COUNT isODD (DROP $1 (MAP SHR $0))))), (lambda (lambda (COUNT isODD (ZIPWITH MIN (DROP $1 $0) $0)))), (lambda (lambda (COUNT isPOS (ZIPWITH MAX (DROP $1 $0) <HOLE>)))), (lambda (lambda (COUNT isODD (DROP <HOLE> (MAP SHR $0))))), (lambda (lambda (COUNT isEVEN (MAP DIV3 (DROP $1 $0))))), (lambda (lambda (COUNT <HOLE> (MAP SHR (DROP $1 $0))))), (lambda (lambda (COUNT isODD (TAKE $1 (MAP SHR $0))))), (lambda (lambda (COUNT isODD (DROP $1 (FILTER isPOS $0))))), (lambda (lambda (COUNT isODD (FILTER isNEG (DROP $1 $0))))), (lambda (lambda (COUNT isEVEN (ZIPWITH MAX (DROP $1 $0) $0)))), (lambda (lambda (COUNT isEVEN (ZIPWITH MIN (DROP $1 $0) $0)))), (lambda (lambda (COUNT isODD (MAP SHR (DROP $1 $0))))), (lambda (lambda (COUNT isODD (DROP $1 (MAP DIV3 $0))))), (lambda (lambda (COUNT isPOS (DROP $1 (REVERSE $0))))), (lambda (lambda (COUNT <HOLE> (DROP $1 (FILTER isPOS $0))))), (lambda (lambda (COUNT isODD (SCANL1 MIN (DROP $1 $0))))), (lambda (lambda (COUNT isODD (ZIPWITH MIN $0 (DROP $1 $0))))), (lambda (lambda (COUNT isEVEN (MAP SHR (DROP $1 $0))))), (lambda (lambda (COUNT isODD (ZIPWITH MAX (DROP $1 $0) $0)))), (lambda (lambda (COUNT isNEG (DROP $1 (FILTER isEVEN $0))))), (lambda (lambda (COUNT isPOS (FILTER isODD (DROP $1 $0))))), (lambda (lambda (COUNT isPOS (DROP $1 (FILTER isODD $0))))), (lambda (lambda (COUNT isPOS (ZIPWITH MIN (DROP $1 $0) $0)))), (lambda (lambda (COUNT isODD (MAP DIV3 (DROP $1 $0))))), (lambda (lambda (COUNT isEVEN (DROP $1 (MAP SHR $0)))))]
Traceback (most recent call last):
  File "compiledDriver.py", line 17, in <module>
    request = pickle.load(sys.stdin.buffer)
  File "/home/yliang/miniconda3/envs/sketch/lib-python/3/pickle.py", line 1571, in _load
    encoding=encoding, errors=errors).load()
  File "/home/yliang/miniconda3/envs/sketch/lib-python/3/pickle.py", line 1070, in load
    dispatch[key[0]](self)
  File "/home/yliang/miniconda3/envs/sketch/lib-python/3/pickle.py", line 1358, in load_global
    klass = self.find_class(module, name)
  File "/home/yliang/miniconda3/envs/sketch/lib-python/3/pickle.py", line 1408, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
Traceback (most recent call last):
  File "eval/evaluate_deepcoder.py", line 195, in <module>
    results = evaluate_dataset(model, dataset, nSamples, mdl, max_to_check, dcModel=dcModel)
  File "eval/evaluate_deepcoder.py", line 137, in evaluate_dataset
    return {datum: list(evaluate_datum(i, datum, model, dcModel, nRepeats, mdl, max_to_check)) for i, datum in enumerate(dataset)}
  File "eval/evaluate_deepcoder.py", line 137, in <dictcomp>
    return {datum: list(evaluate_datum(i, datum, model, dcModel, nRepeats, mdl, max_to_check)) for i, datum in enumerate(dataset)}
  File "eval/evaluate_deepcoder.py", line 123, in evaluate_datum
    enum_results, n_checked, n_hit = pypy_enumerate(untorch(g), datum.tp, datum.IO, mdl, sketchtups, n_checked, n_hit, t, max_to_check)
  File "/home/yliang/neural_sketch/util/pypy_util.py", line 50, in pypy_enumerate
    return callCompiled(dc_enumerate, tp, IO, mdl, sketchtups, n_checked, n_hit, t, max_to_check)
  File "/home/yliang/neural_sketch/ec/utilities.py", line 325, in callCompiled
    success, result = pickle.load(p.stdout)
EOFError: Ran out of input
```

**Comment by mtensor** [comment]
The code is written so that callCompiled executes a pypy process to enumerate (so that enumeration is faster than native cPython). It's possible that the "No module named 'numpy'" error is because you don't have numpy installed on your pypy installation.

Alternatively, callCompiled could be rewritten (or removed entirely) so that native cPython is run instead, and pypy isn't used at all.
